// src/components/HeritageStorySection.vue
<template>
  <section id="story" class="py-20 bg-[#1C2622] text-[#FDFCFB] border-b border-[#333333]">
    <div class="max-w-7xl mx-auto px-4 sm:px-8">
      <div class="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
        <!-- Left: Story Narrative Column -->
        <div class="lg:col-span-7 flex flex-col">
          <div class="inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.25em] text-[#C5A059] mb-4">
            <span class="w-8 h-[1px] bg-[#C5A059]"></span>
            <span>40+ Years of Holyrood Roots</span>
          </div>

          <h2 class="font-serif text-3xl sm:text-4xl lg:text-5xl font-normal leading-tight mb-6 text-white">
            {{ story.heading }}
          </h2>

          <p class="text-sm sm:text-base text-[#C5A059] font-medium mb-6">
            {{ story.subheading }}
          </p>

          <div class="space-y-4 text-xs sm:text-sm text-gray-300 font-light leading-relaxed mb-8">
            <p v-for="(paragraph, pIdx) in story.paragraphs" :key="pIdx">
              {{ paragraph }}
            </p>
          </div>

          <!-- Highlight Quote Box -->
          <div class="bg-white/5 border-l-2 border-[#C5A059] p-5 my-2">
            <p class="font-serif italic text-base sm:text-lg text-white font-light">
              {{ story.quote }}
            </p>
            <span class="text-[10px] uppercase tracking-widest text-[#C5A059] font-semibold mt-2 block">
              — Lori & Rob Condon, Hi Haven Manor
            </span>
          </div>
        </div>

        <!-- Right: Historic Timeline / Feature Milestones & Official Sign Photo -->
        <div class="lg:col-span-5 flex flex-col gap-6">
          <!-- Official Entrance Sign Photo Card -->
          <div class="bg-[#233B31] border border-white/10 overflow-hidden shadow-md">
            <div class="aspect-4/3 relative flex items-center justify-center bg-black/40">
              <img 
                v-if="signImg"
                :src="signImg" 
                alt="Hi Haven Manor Entrance Sign at 36 Butterpot Road" 
                referrerPolicy="no-referrer"
                class="w-full h-full object-cover"
              />
              <div v-else class="p-8 text-center text-white">
                <span class="text-[10px] uppercase font-mono tracking-widest text-[#C5A059] block mb-1">Hi Haven Manor Sign</span>
                <p class="font-serif text-lg">36 Butterpot Road</p>
                <span class="text-xs text-gray-300">Holyrood, NL • (709) 229-7992</span>
              </div>
              <div class="absolute bottom-0 inset-x-0 bg-gradient-to-t from-black/80 to-transparent p-3 text-white">
                <span class="text-[10px] uppercase font-mono tracking-widest text-[#C5A059]">36 Butterpot Road, Holyrood, NL</span>
                <p class="text-xs font-serif">Hi Haven Manor Entrance Sign</p>
              </div>
            </div>
          </div>

          <div class="bg-[#233B31] border border-white/10 p-7 shadow-md">
            <h3 class="font-serif text-xl text-white mb-5 pb-3 border-b border-white/10">
              Heritage Milestones
            </h3>

            <div class="space-y-5">
              <div class="flex items-start gap-3">
                <span class="font-mono text-xs text-[#C5A059] font-bold shrink-0 pt-0.5">1980s</span>
                <div>
                  <h4 class="text-xs font-semibold text-white">Woodland Motel, Cabins & Tavern</h4>
                  <p class="text-[11px] text-gray-300 font-light mt-0.5">
                    Originally operated as a beloved Holyrood gathering point for travellers, campers, and local workers.
                  </p>
                </div>
              </div>

              <div class="flex items-start gap-3">
                <span class="font-mono text-xs text-[#C5A059] font-bold shrink-0 pt-0.5">2000s</span>
                <div>
                  <h4 class="text-xs font-semibold text-white">Supportive Living Transformation</h4>
                  <p class="text-[11px] text-gray-300 font-light mt-0.5">
                    Transitioned into a dedicated residential care home for adults requiring daily personal assistance and supportive supervision.
                  </p>
                </div>
              </div>

              <div class="flex items-start gap-3">
                <span class="font-mono text-xs text-[#C5A059] font-bold shrink-0 pt-0.5">2015</span>
                <div>
                  <h4 class="text-xs font-semibold text-white">Comprehensive Modernization & Renovations</h4>
                  <p class="text-[11px] text-gray-300 font-light mt-0.5">
                    Comprehensive structural and interior renovations updated the home while preserving its down-home warmth.
                  </p>
                </div>
              </div>

              <div class="flex items-start gap-3">
                <span class="font-mono text-xs text-[#C5A059] font-bold shrink-0 pt-0.5">Today</span>
                <div>
                  <h4 class="text-xs font-semibold text-white">Eastern Health Subsidized Community Home</h4>
                  <p class="text-[11px] text-gray-300 font-light mt-0.5">
                    Operating with 15 resident beds under Eastern Health's Mental Health and Addiction program, providing certified 24/7 care.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup>
import { ref, onMounted } from 'vue';
import { ABOUT_US_STORY } from '../data/hiHavenData.js';

const story = ABOUT_US_STORY;

const signImg = ref(localStorage.getItem('hihaven_photo_photo-5') || '');

onMounted(() => {
  window.addEventListener('storage', () => {
    signImg.value = localStorage.getItem('hihaven_photo_photo-5') || '';
  });
});
</script>

// src/components/HeritageStorySection.tsx
import React from 'react';
import { BUSINESS_INFO, ABOUT_US_STORY } from '../data/hiHavenData';
import { ShieldCheck, HeartHandshake, Home, MapPin, Award, Users, CheckCircle2, Stethoscope, Sparkles } from 'lucide-react';
import hiHavenExterior from '../assets/images/hi_haven_exact_screenshot.png';


export const HeritageStorySection: React.FC = () => {
  return (
    <section className="py-20 sm:py-24 bg-[#F3EFEA] border-b border-[#E5DFC5]" id="about" aria-labelledby="heritage-heading">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 lg:gap-16 items-center">
          
          {/* Left Column: Visual Portrait & History Card */}
          <div className="lg:col-span-5">
            <div className="relative">
              <div className="overflow-hidden rounded-md border border-[#E5DFC5] bg-white shadow-sm aspect-[4/3]">
                <img
                  src={hiHavenExterior}
                  alt="Hi Haven Manor building nestled in trees in Holyrood, NL"
                  loading="lazy"
                  className="w-full h-full object-cover"
                />
              </div>

              {/* Heritage Note Card */}
              <div className="mt-6 bg-white p-6 sm:p-7 border border-[#E5DFC5] shadow-xs">
                <div className="flex items-center justify-between mb-2">
                  <span className="text-[10px] uppercase tracking-[0.2em] text-[#8C705B] font-bold">
                    40+ Year Holyrood Heritage
                  </span>
                  <span className="text-[11px] bg-[#FAF8F5] text-[#233B31] font-semibold px-2 py-0.5 border border-[#E5DFC5]">
                    Updated 2015
                  </span>
                </div>
                <p className="text-sm font-serif text-[#1C2622] italic leading-relaxed">
                  "We offer a long-term home and surrogate family setting where every resident is treated with dignity, kindness, and personal respect."
                </p>
                <div className="mt-3 pt-3 border-t border-[#E5DFC5]/60 flex items-center justify-between">
                  <p className="text-xs uppercase tracking-wider text-[#5F6B65] font-medium">
                    Hi Haven Manor • Holyrood, NL
                  </p>
                  <span className="text-[11px] text-[#233B31] font-medium">15 Beds Max</span>
                </div>
              </div>
            </div>
          </div>

          {/* Right Column: Narrative & Values */}
          <div className="lg:col-span-7">
            <div className="flex items-center gap-3 mb-4">
              <span className="text-[11px] uppercase tracking-[0.3em] text-[#5F6B65] font-semibold">
                ABOUT HI HAVEN MANOR
              </span>
              <div className="h-[1px] w-8 bg-[#233B31]"></div>
            </div>

            <h2 className="font-serif text-3xl sm:text-4xl lg:text-5xl font-normal text-[#1C2622] leading-[1.1] mb-6" id="heritage-heading">
              {ABOUT_US_STORY.headline}
            </h2>

            <div className="space-y-4 text-sm sm:text-base text-[#5F6B65] leading-relaxed font-light">
              <p>
                <strong>Hi Haven Manor</strong> has been a family-run business in Holyrood for over 40 years. Originally, the property was a beloved tavern and motel with cabins for visitors to stay in and grounds for camping. Following the closure of the local refinery, Hi Haven Manor was transitioned into a dedicated residential care home.
              </p>

              <p>
                In <strong>2015</strong>, it came under new owners and management who made extensive updates and modern renovations to the building, accommodations, and community facilities.
              </p>

              <p>
                Operating under the <strong>Mental Health and Addiction program of Eastern Health (NL Health Services)</strong>, our program is <strong>government subsidized</strong>, meaning that potential residents and their families can apply for provincial financing.
              </p>


              <p>
                We aim to provide a comprehensive care plan for each of our residents through supportive, recreational, medical, and psychosocial services. We assist residents to reach their maximum potential for growth and self-determination in a comfortable, surrogate family setting.
              </p>

              <p>
                We are also delighted to note that several of our staff members have completed their certified <strong>PCA (Personal Care Attendant)</strong> course, ensuring knowledgeable and compassionate daily care.
              </p>
            </div>

            {/* 3 Core Operational Principles */}
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mt-8 pt-6 border-t border-[#E5DFC5]">
              <div className="bg-white p-4 border border-[#E5DFC5]">
                <div className="flex items-center gap-1.5 mb-1.5 text-[#233B31]">
                  <Users className="w-4 h-4" />
                  <h3 className="text-xs uppercase tracking-wider font-semibold text-[#1C2622]">Surrogate Family</h3>
                </div>
                <p className="text-xs text-[#5F6B65] font-light leading-relaxed">
                  Treating each resident and staff member as family, with visits from loved ones warmly encouraged.
                </p>
              </div>

              <div className="bg-white p-4 border border-[#E5DFC5]">
                <div className="flex items-center gap-1.5 mb-1.5 text-[#233B31]">
                  <Stethoscope className="w-4 h-4" />
                  <h3 className="text-xs uppercase tracking-wider font-semibold text-[#1C2622]">Weekly Doctor & PCAs</h3>
                </div>
                <p className="text-xs text-[#5F6B65] font-light leading-relaxed">
                  Weekly community General Practitioner visits, psychiatric specialist access, and certified PCAs.
                </p>
              </div>

              <div className="bg-white p-4 border border-[#E5DFC5]">
                <div className="flex items-center gap-1.5 mb-1.5 text-[#233B31]">
                  <ShieldCheck className="w-4 h-4" />
                  <h3 className="text-xs uppercase tracking-wider font-semibold text-[#1C2622]">Self-Determination</h3>
                </div>
                <p className="text-xs text-[#5F6B65] font-light leading-relaxed">
                  Supervision is no greater than necessary with the goal of active integration into the community.
                </p>
              </div>
            </div>

          </div>

        </div>
      </div>
    </section>
  );
};
