// src/components/TrustStandardsAccreditation.vue
<template>
  <section id="standards" class="py-20 bg-[#F3EFEA] border-b border-[#E5DFC5]">
    <div class="max-w-7xl mx-auto px-4 sm:px-8">
      <div class="text-center max-w-2xl mx-auto mb-16">
        <span class="text-xs font-semibold uppercase tracking-[0.25em] text-[#C5A059] block mb-2">
          Safety, Compliance & Oversight
        </span>
        <h2 class="font-serif text-3xl sm:text-4xl text-[#1C2622] font-normal leading-tight mb-4">
          Provincial Standards You Can Trust
        </h2>
        <p class="text-sm sm:text-base text-[#5F6B65] font-light">
          Hi Haven Manor adheres strictly to Newfoundland & Labrador health, fire, safety, and certified attendant standards.
        </p>
      </div>

      <!-- Standards Grid -->
      <div class="grid grid-cols-1 md:grid-cols-2 gap-6 max-w-5xl mx-auto">
        <div 
          v-for="std in standards" 
          :key="std.id"
          class="bg-white border border-[#E5DFC5] p-7 shadow-sm flex flex-col justify-between"
        >
          <div>
            <div class="inline-block px-2.5 py-1 bg-[#FAF8F5] border border-[#E5DFC5] text-[10px] uppercase tracking-wider font-semibold text-[#C5A059] mb-3">
              {{ std.badge }}
            </div>
            <h3 class="font-serif text-xl text-[#1C2622] mb-2">
              {{ std.title }}
            </h3>
            <p class="text-xs text-[#5F6B65] font-light leading-relaxed mb-4">
              {{ std.description }}
            </p>
            <ul class="space-y-1.5 text-xs text-[#2A3631] border-t border-[#E5DFC5]/60 pt-3">
              <li v-for="(d, dIdx) in std.details" :key="dIdx" class="flex items-start gap-2">
                <span class="text-emerald-700 font-bold">✓</span>
                <span>{{ d }}</span>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup>
import { ACCREDITATION_STANDARDS } from '../data/hiHavenData.js';

const standards = ACCREDITATION_STANDARDS;
</script>

// src/components/TrustStandardsAccreditation.tsx
import React from 'react';
import { ACCREDITATION_STANDARDS } from '../data/hiHavenData';
import { ShieldCheck, CheckCircle2, Award, FileCheck, Landmark, Check } from 'lucide-react';

export const TrustStandardsAccreditation: React.FC = () => {
  return (
    <section className="py-20 sm:py-24 bg-[#F3EFEA] border-b border-[#E5DFC5]" id="standards" aria-labelledby="standards-heading">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Section Header */}
        <div className="max-w-3xl mb-14">
          <div className="flex items-center gap-3 mb-3">
            <span className="text-[11px] uppercase tracking-[0.3em] text-[#5F6B65] font-semibold">
              STANDARDS & ACCREDITATION
            </span>
            <div className="h-[1px] w-8 bg-[#233B31]"></div>
          </div>
          <h2 className="font-serif text-3xl sm:text-4xl lg:text-5xl font-normal text-[#1C2622] leading-[1.1] mb-4" id="standards-heading">
            Licensed care you can trust with confidence.
          </h2>
          <p className="text-sm sm:text-base text-[#5F6B65] leading-relaxed font-light">
            Trust is earned through transparency and accountability. Hi Haven Manor operates under strict Provincial Personal Care Home standards, routine public health and fire safety inspections, and verified staff credentialing.
          </p>
        </div>

        {/* Standards Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          {ACCREDITATION_STANDARDS.map((standard, index) => {
            const numberLabel = `0${index + 1}`;
            return (
              <div
                key={standard.id}
                className="bg-white p-6 border border-[#E5DFC5] flex flex-col justify-between"
                id={`standard-card-${standard.id}`}
              >
                <div>
                  <div className="flex items-start justify-between gap-3 mb-4">
                    <span className="inline-flex items-center gap-1.5 text-[9px] font-semibold uppercase tracking-wider text-[#233B31] bg-[#FAF8F5] px-2.5 py-1 border border-[#E5DFC5]">
                      {standard.status}
                    </span>
                    <span className="text-xs font-serif text-[#8C705B]">
                      {numberLabel}
                    </span>
                  </div>

                  <h3 className="font-serif text-lg font-normal text-[#1C2622] mb-1">
                    {standard.title}
                  </h3>

                  <p className="text-[10px] uppercase tracking-wider text-[#5F6B65] font-medium mb-3 flex items-center gap-1">
                    <Landmark className="w-3 h-3 text-[#233B31]" />
                    <span>{standard.authority}</span>
                  </p>

                  <p className="text-xs text-[#5F6B65] leading-relaxed mb-5 font-light">
                    {standard.description}
                  </p>
                </div>

                <div className="pt-4 border-t border-[#E5DFC5]/60">
                  <ul className="space-y-2">
                    {standard.details.map((detail, idx) => (
                      <li key={idx} className="flex items-start gap-2 text-xs text-[#5F6B65]">
                        <Check className="w-3.5 h-3.5 text-[#233B31] mt-0.5 flex-shrink-0" />
                        <span>{detail}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            );
          })}
        </div>

      </div>
    </section>
  );
};
